import React, { forwardRef } from 'react';
import { useSelector } from 'react-redux';
import { formatCurrency, formatPercentage } from '../utils/formatters';

const PDFContent = forwardRef((props, ref) => {
  const { data, metrics } = useSelector((state) => state.portfolio);
  const currentDate = new Date().toLocaleDateString();

  return (
    <div ref={ref} style={{ padding: '40px', fontFamily: 'Arial, sans-serif' }}>
      <h1 style={{ textAlign: 'center', marginBottom: '20px' }}>Portfolio Report</h1>
      <p>Generated on: {currentDate}</p>

      {/* Portfolio Overview */}
      <h2>Portfolio Overview</h2>
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '10px', marginBottom: '20px' }}>
        <div>
          <p>Total Value: {formatCurrency(metrics.totalValue)}</p>
          <p>Total Gain/Loss: {formatCurrency(metrics.totalGain)}</p>
        </div>
        <div>
          <p>ROI: {formatPercentage(metrics.roi)}</p>
          <p>Daily Change: {formatPercentage(metrics.dailyChange)}</p>
        </div>
      </div>

      {/* Risk Metrics */}
      <h2>Risk Analysis</h2>
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '10px', marginBottom: '20px' }}>
        <div>
          <p>Volatility: {metrics.volatility.toFixed(2)}%</p>
          <p>Beta: {metrics.beta.toFixed(2)}</p>
        </div>
        <div>
          <p>Sharpe Ratio: {metrics.sharpeRatio.toFixed(2)}</p>
          <p>Max Drawdown: {metrics.maxDrawdown.toFixed(2)}%</p>
        </div>
      </div>

      {/* Holdings Table */}
      <h2>Portfolio Holdings</h2>
      <table style={{ width: '100%', borderCollapse: 'collapse', marginBottom: '20px' }}>
        <thead>
          <tr>
            <th style={{ textAlign: 'left', padding: '8px', borderBottom: '1px solid #ddd' }}>Asset</th>
            <th style={{ textAlign: 'right', padding: '8px', borderBottom: '1px solid #ddd' }}>Value</th>
            <th style={{ textAlign: 'right', padding: '8px', borderBottom: '1px solid #ddd' }}>Weight</th>
            <th style={{ textAlign: 'right', padding: '8px', borderBottom: '1px solid #ddd' }}>Return</th>
          </tr>
        </thead>
        <tbody>
          {data.holdings.map((holding, index) => (
            <tr key={index}>
              <td style={{ padding: '8px', borderBottom: '1px solid #ddd' }}>{holding.asset}</td>
              <td style={{ textAlign: 'right', padding: '8px', borderBottom: '1px solid #ddd' }}>
                {formatCurrency(holding.currentValue)}
              </td>
              <td style={{ textAlign: 'right', padding: '8px', borderBottom: '1px solid #ddd' }}>
                {formatPercentage(holding.weight)}
              </td>
              <td style={{ textAlign: 'right', padding: '8px', borderBottom: '1px solid #ddd' }}>
                {formatPercentage(holding.return)}
              </td>
            </tr>
          ))}
        </tbody>
      </table>

      <p style={{ textAlign: 'right', fontSize: '12px', marginTop: '40px' }}>
        Report generated by Wealth Management Dashboard
      </p>
    </div>
  );
});

PDFContent.displayName = 'PDFContent';
export default PDFContent;
